# Generated by Django 5.2.7 on 2025-11-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_city_customuser_country_customuser_genres_and_more'),
        ('gigs', '0002_tag_gig_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='instruments',
        ),
        migrations.AddField(
            model_name='customuser',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='users', to='gigs.tag'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('creator', 'Creator'), ('organizer', 'Organizer')], default='musician', max_length=20),
        ),
    ]
