# Generated by Django 5.2.7 on 2025-11-14 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_blocked_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='blocked_users',
            new_name='blocks',
        ),
    ]
