# Generated by Django 5.2.7 on 2025-11-05 15:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0004_tag_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='gigapplication',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='gigapplication',
            unique_together={('applicant', 'gig')},
        ),
    ]
